version: '3.9'
services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"
    restart: always
  
  nats-cli:
    image: synadia/nats-box
    container_name: nats-cli
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true
