version: '3.9'
services:
  nats:
    image: nats
    container_name: nats
    # http://localhost:8222
    ports:
      - "4222:4222"
      - "8222:8222"  # HTTP management port
    restart: always
  
  nats-cli:
    image: synadia/nats-box
    container_name: nats-cli
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true
